apiVersion: v1
kind: ConfigMap
metadata:
  name: novel-config
  namespace: default
data:
  JWT_SECRET: "9CvsyDGtiBzYB7SgmnDKZcmYtKFkUdEL"
  ADMIN_JWT_SECRET: "9CvsyDGtiBAYB7SgmSDKZcmYtKFkUdEL"
  MYSQL_HOST: "127.0.0.1"
  MYSQL_USER: "root"
  MYSQL_PASSWD: "smd013012"
  MYSQL_NOVEL_DB: "novel"
  MYSQL_ADMIN_DB: "admin"
  MYSQL_LOG: "true"
  MYSQL_PORT: "3306"
  ETCD_HOST: "127.0.0.1"
  ETCD_PORT: "32379"
  TRACER_HOST: "127.0.0.1"
  TRACER_PORT: "5775"
  PAYPAL_CLIENT_ID: "AUKksEwIifzBH-AvcR0O-aegcC_N3xUWoctlZmrUjO6nWGNpTgZqJJ7ZoGE3Ngy3HnlRZgkWt0ibXm4N"
  PAYPAL_SECRET: "EPg-JoN-qXeIi6oVyjZBI31lGOB_nXmB9N1DYgMMyiRiQySo23VKS-2Gz2qr2EzbrAnTvTTsG2RYSr_i"
  PAYPAL_RETURN_URL: "http://www.556wan.cn/charge/callback/USD"
  PAYPAL_ENV: "local"
  ALIPAY_APPID: "2019052465357270"
  ALIPAY_RSA_PRIVATE_KEY: "MIIEowIBAAKCAQEA0k8yjiMl8hjwq+McVAWL1LXZD1JqI7fM5tKHijD9f3Wy4FeYZs7gAFmy85rbSnEUID7oWsC9nii29T07AIiHG67rY6vKzlEnynxCwkXFA3OITj4eMnWZlQiGdV42kBQIXwuvl4LReBHCBE1hJjSgdeYGpEuyzhKP7APNM4pMpIC88VCXsM27bE4LikXyYj5YXiJflyXshYnaKyjFprF8LdZZxM/sxHsIdRrvavoYttoUTjvZollXFE4sDbz+B30Bds5iQG15yMJdNtkDtSauhgwxhcRuk8pW/dR1AUTzWGBT4HwkBKtphSHfK12aqG4LHNt6qfx0Pb8Eia83+KBlHwIDAQABAoIBAQCR7hhzXlo/MiUV8GJAvxR3BbPXGOXDYQ9R/zXDoxjTb7UuTDnY5KW0OIme1Y5iijJf6abLCkDI1RGW++TMCvBNOkPlhlgUb2W/8BdWvJjnOyyStjG367glHKRIHpaXxP7GDNLLvB9jRFcvKw5FN3E8Pd/P8yLgMSsipsSlhcqGvfcAiIF3iOPke0J1JTdAYUq0JkwoZmGZxSuqFpayo7/7bFm2J7npoDtgLyKo/umAYRB4Occ5tkOyu9QV+F3xkAB2IvpiLflof7PirAL4hADG0DNvuWyGVfaAt1NKJZ2XR/dWUIaBRvXZUpPU7GuRa6q5fTTtDtMA+cqTfa2ocFD5AoGBAPmDw7sPpFeuxjTXFBjPLGbbKdah8hkgOBnGv7JaTB1kpnUfJ6yGdlk9y97qdK031qLSep6sG9WI/6Wu6LHkhXnGoIXaIjHHBa/880FG2QwWKRUJsDdGxqrqjDsPdAzwVK5E6FdBF/ovwgNG7IaGt+yTkRrjZiVQsRD+Carf6yPjAoGBANfGkO6TeAOTYcc3d22JOgqn7DL4K/j/8Ic3yMQp6bidQ5zHSnPP04iXBhcu+DDQHS6b/k1HA8SV4x2c4V6Yk/p45TLPno9vuZQLH3JX1hGRw/H0WQG3HaRNhotlClyJJjV5CSQ4BkInyk5AjLSONPBoVgTnRIGUwHhK2C6GxRaVAoGAE0WwKpSstvES8iXisX/fCBrJgoCDuJkafDMzv0zmMCcEDGvZnqPMJFx3kMI/PNnhRDZJrlPQ2o94X43A/2yNOriy0WPl3D5pHAzHpTUZsqtLhQp4h+x5j94J8s3gwtcVU1iTMZofhf2GWMZzonhpYGaNgKwryZoP8yYMDRy6hs0CgYBVAqo/FGKIJhyzvCqVQSdY42evfQ71/v/ohhXXExw929ezgODYV9zjR3zizWKC+LtGjbbXA098uADOvewctMg4OkEyj5HMuRvIM8mj5u8z5NXqEXavslE/VjvX12sJog8nqhPr7RaqIbsWsV++EvjQborVS7g1xUE/I12glwA3MQKBgDunVnRoPO38lbQo65TRd79nXQkH09le5uAM/Htno2MXa4nY1o6ductVt8paoaTk++QpDRZfjCOLpSxrfv5l2dQ/OlHJSKbYLDTkulscAoqDTzhhf+B0MNWxJ3Eu79/0Ewv/pEkV4HIlua1BCWR6H9xliB8pSjTwrTCHzxs/aaw6"
  ALIPAY_RSA_PUBLIC_KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvK+7eqJMihFAzhtO+p635MQW2/En+uLcmKuqUJ00B/1Q+TZwzn8WKNY+HDTRHj9KlqSgh5tpgZVNSCXGpgXWYmTklmwQXcSQ5v4Y14o2nG0CQz3mZPI2Eu69aELp7Xtxb//I5h0H91RF8pvnh7oQe1wZAq/X036LIXdk7pjxU4yhBa5hK+T+OwnPIc3oNOIz9vubJwkavYaG7QyCxSjQi/LhZXLqGYCLCiuUUshVzB0RZy3vdUYDP6Y5Epvu9elmILfgdEaqBpTDGBOz3gFAMR/Ecu3AmQum20A/yPNrR9P2eETucIX3zmz4XaF+ZN+KhiZdos5H7jc+rMIuDGQNNwIDAQAB"
  ALIPAY_NOTIFY_URL: "http://www.556wan.cn/charge/callback"
